package br.com.compreseucarroaqui.domain;

// Generated Jan 31, 2017 4:01:41 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Pagamento generated by hbm2java
 */
@Entity
@Table(name = "PAGAMENTO")
public class Pagamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PagamentoId id;
	private String datadasaida;

	public Pagamento() {
	}

	public Pagamento(PagamentoId id, String datadasaida) {
		this.id = id;
		this.datadasaida = datadasaida;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "cpf", column = @Column(name = "CPF", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "chassi", column = @Column(name = "CHASSI", nullable = false, precision = 22, scale = 0)) })
	public PagamentoId getId() {
		return this.id;
	}

	public void setId(PagamentoId id) {
		this.id = id;
	}

	@Column(name = "DATADASAIDA", nullable = false, length = 10)
	public String getDatadasaida() {
		return datadasaida;
	}

	public void setDatadasaida(String datadasaida) {
		this.datadasaida = datadasaida;
	}

	@Override
	public String toString() {
		return "Pagamento [id=" + id.getCpf() +" chassi ="+id.getChassi()+ ", datadasaida=" + datadasaida + "]";
	}
	
	
		
}
